In [3]:
import numpy as np

a1 = np.array([[1, 2, 3], [10, 20, 30]])
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
6


In [64]:
a2 = np.arange(20).reshape(4, 5)
print(a2)
print(a2.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [26]:
print(a2)

a3 = a2.flatten()         # 본래 배열엔 영향이 없음
a3[3] = 100
print(a3)
print(a2)

a4 = a2.ravel()           # 본래 배열 인덱스도 바꿔버림
a4[3] = 200
print(a4)
print(a2)

[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[  0   1   2 200   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [27]:
a2 = np.arange(20).reshape(4, 5)
print(a2)
# print(a2.shape)
# print(a2[1])
# print(a2[1, 2])
# print(a2[:, 1])
print(a2[:, 1:4])
print(a2[:, 1:4:2])
print(a2[1:3, :])
print(a2[::2, :])
print(a2[::2, 1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[ 1  2  3]
 [11 12 13]]


In [34]:
print(a2)
print(a2.shape)      # aixs
print(a2.sum())
print(a2.sum(axis = 0))
print(a2.sum(axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
190
[30 34 38 42 46]
[10 35 60 85]


In [41]:
print(a2, a3.shape)
a3 = a2.T    # transformation : x, y 축 바꿈
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (5, 4)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [42]:
print(a2, a2.shape)
np.moveaxis(a2, [0], [1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [48]:
a10 = np.arange(5,20)
print(a10, a10.shape)

# shape (3,5) 의 차원 ndarray로 만들기
a10 = np.arange(5,20).reshape(3,5)
print(a10, a10.shape)

a11 = a10[:, 2:4]
print(a11)
print(a11, a11.shape)
print(a11.sum(axis = 0))
print(np.mean(a11, axis = 0))     # numpy doc 참고

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] (15,)
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (3, 5)
[[ 7  8]
 [12 13]
 [17 18]]
[[ 7  8]
 [12 13]
 [17 18]] (3, 2)
[36 39]
[12. 13.]


In [58]:
a1 = np.arange(0, 10).reshape(2, 5)
a2 = np.arange(100, 110).reshape(2, 5)
print(a1)
print(a2)
a3 = np.concatenate((a1, a2), axis = 1)
a3_1 = np.concatenate((a1, a2), axis = 0)
print(a3)
print(a3_1)
a4 = np.hstack((a1, a2))    # horizon
print(a4)
a5 = np.vstack((a1, a2))    # vertical
print(a5)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 101 102 103 104]
 [105 106 107 108 109]]
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 101 102 103 104]
 [105 106 107 108 109]]
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 101 102 103 104]
 [105 106 107 108 109]]


In [62]:
print(a4)
a6 = np.hsplit(a4,5)
print(a6)

[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[array([[0, 1],
       [5, 6]]), array([[2, 3],
       [7, 8]]), array([[  4, 100],
       [  9, 105]]), array([[101, 102],
       [106, 107]]), array([[103, 104],
       [108, 109]])]


In [65]:
a7 = a4.T
print(a7)
np.vsplit(a7, 5)

[[  0   5]
 [  1   6]
 [  2   7]
 [  3   8]
 [  4   9]
 [100 105]
 [101 106]
 [102 107]
 [103 108]
 [104 109]]


[array([[0, 5],
        [1, 6]]),
 array([[2, 7],
        [3, 8]]),
 array([[  4,   9],
        [100, 105]]),
 array([[101, 106],
        [102, 107]]),
 array([[103, 108],
        [104, 109]])]

In [71]:
a2 = np.arange(20).reshape(4,5)
print(a2)

filter1 = a2[:, 0] % 10 == 5
print(a2[filter1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
