In [3]:
import numpy as np

a1 = np.array([[1, 2, 3], [10, 20, 30]])
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
6


In [29]:
a2 =np.arange(20).reshape(4, 5)
print(a2)
print()
#print(a2.shape)
print()
# print(a2[1])
# print(a2[1, 2])
# print(a2[:, 1])
# print(a2[:, 1:4])
# print(a2[:, 1:4:2])
# print(a2[1, :])
# print(a2[1:3, :])
# print(a2[::2, :])
print(a2[::2, 1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[ 1  2  3]
 [11 12 13]]


In [34]:
print(a2)
# print(a2.shape)  # axis
# print(a2.sum())
print(a2.sum(axis=0))
print(a2.sum(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]
[10 35 60 85]


In [35]:
print(a2, a3.shape)
a3 = a2.T
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (20,)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [36]:
print(a2, a2.shape)
np.moveaxis(a2, [0], [1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [13]:
a3 = a2.flatten() #표면으로 보이는 자신만 바꾼다.

a3[3] = 100
print(a3)
print(a2)

a4 = a2.ravel() #참조값까지 바꾼다.

a4[3] = 200
print(a4)
print(a2)


[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[  0   1   2 200   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [45]:
a10 = np.arange(5,20)
print(a10, a10.shape)

# shape (3,5) 의 차원 ndarray로 만들기
a10 = np.arange(5,20).reshape(3,5)
print(a10, a10.shape)

print(a10[:, 2:4])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] (15,)
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (3, 5)
[[ 7  8]
 [12 13]
 [17 18]]
